tunnel: 66913219-c502-43ee-9342-56985c731a87
credentials-file: /home/yadurajdoc/.cloudflared/66913219-c502-43ee-9342-56985c731a87.json

ingress:
  # Route API subdomain to backend
  - hostname: plasticworld.yaduraj.me
    service: http://localhost:3000
  
  # Catch-all rule (must be last)
  - service: http_status:404
